@xsuaaHostname = https://XXX.authentication.RRR.hana.ondemand.com
@btpXsuaaClient = CLIENT
# 下記Secretはデプロイのたびに変わる
@btpXsuaaSecret = SECRET
@btpAppHostname = https://XXX.cfapps.RRR.hana.ondemand.com


### GET XSUAA TOKEN

# @name getXsuaaToken
POST {{xsuaaHostname}}/oauth/token
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{btpXsuaaClient}}:{{btpXsuaaSecret}}

client_id={{btpXsuaaClient}}
&client_secret={{btpXsuaaSecret}}
&grant_type=client_credentials


### ADD MAILS I
@token = {{getXsuaaToken.response.body.$.access_token}}

### Get Data from QAhistory
GET {{btpAppHostname}}/odata/v4/GPT/Qahistory
Authorization: Bearer {{token}}
Accept: application/json

### Add Data to QAhistory
POST {{btpAppHostname}}/odata/v4/GPT/Qahistory
Authorization: Bearer {{token}}
Content-Type: application/json; charset=utf-8

{
    "question": "SAP HANAとは何ですか？",
    "answer": "SAP HANAはインメモリデータベース管理システムです。",
    "mergedqa": "Q: SAP HANAとは何ですか？ A: SAP HANAはインメモリデータベース管理システムです。",
    "metadata": "{\"source\": \"FAQ\", \"created_by\": \"admin\"}"
}
