-- DROP TABLE GPTSERVICE_QAHISTORY;

CREATE TABLE GPTSERVICE_QAHISTORY (
    ID NVARCHAR(36) PRIMARY KEY DEFAULT SYSUUID,
    METADATA NCLOB,
    QUESTION NCLOB,
    ANSWER NCLOB,
    MERGEDQA NVARCHAR(5000),
    SAP_EMBEDDING REAL_VECTOR GENERATED ALWAYS AS VECTOR_EMBEDDING(MERGEDQA, 'DOCUMENT', 'SAP_NEB.20240715'),
    CUSTOM_EMBEDDING REAL_VECTOR DEFAULT NULL,
    -- 下記、本来はCAPから自動で作成されるカラム
    CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- (CAPから更新)
    CREATEDBY NVARCHAR(100) DEFAULT NULL, -- (CAPから更新)
    MODIFIEDBY NVARCHAR(100) DEFAULT NULL -- (CAPから更新)
);