@basicAuthUser = XXX
@basicAuthPassword = XXX
@btpAppHostname = https://XXX.cfapps.RRR.hana.ondemand.com
# @btpAppHostname = http://localhost:5000

### Chat Endpoint
POST {{btpAppHostname}}/chat
# Authorization: Basic {{basicAuthUser}}:{{basicAuthPassword}}
Content-Type: application/json; charset=utf-8

{
    "question": "SAP HANAとは何ですか？"
}

### Agent Endpoint
POST {{btpAppHostname}}/chain
Content-Type: application/json; charset=utf-8

{
    "question": "SAP BTP Hackathonについて質問です。SAP AI Launchpadに「Generatie AI Hub」のメニューが表示されていないのですが、考えられる原因はなんですか？",
    "mode": "SAP",
    "history": []
}

# POST {{btpAppHostname}}/getSimilarity
# # Authorization: Basic {{basicAuthUser}}:{{basicAuthPassword}}
# Content-Type: application/json; charset=utf-8

# {
#     "content1": "SAP HANA Cloudとはなんですか？また、2の10乗を計算してください。",
#     "content2": "空ってなんで青いの？",
#     "mode": "SAP"
# }
